run:
  timeout: 5m

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  unused:
    check-exported: false
  unparam:
    check-exported: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Disable typecheck for now due to module resolution issues
    # - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    - path: internal/config/config\.go
      linters:
        - typecheck
